### ISSUE TITLE
Detect default api_configs.api_url

### ISSUE THREAD

**Issue by jayvdb** [iashraful/fast-drf#10]
Currently it is mandatory to have the following on each model:

```py
    @classmethod
    def exposed_api(cls, *args, **kwargs):
        api_configs = {
            "api_url": 'my-model-api',
        }
        return api_configs
```

While most production sites will want to customise the urls, it is possible to derive a sensible default from the model class name, making it possible to add models to the API by only adding the mixin.  Much faster.  And even in production sites, there will be some parts of the API for which the default model name is an acceptable URI name, especially for smaller models.

**Comment by iashraful** [comment]
Do you really need API for every model? So, `exposed_api` is mandatory to enabled the API for the specific model. I guess I understand what did you say. If not please clarify me a little bit more.

**Comment by jayvdb** [comment]
If I dont want the model in the API, I wouldnt use the Mixin.

**Comment by iashraful** [comment]
Yes. If you don't want an API for a model don't use the mixin.

**Comment by jayvdb** [comment]
This issue is about when I have used the Mixin, I have already decided that I do want the model in the API, so the Mixin can automatically use sensible defaults without any mandatory `exposed_api `.  Thus making it much easier for people to adopt `fast-drf`.

**Comment by iashraful** [comment]
I got your point. That would be nice I think. I hope I'll do it soon.

**Comment by iashraful** [comment]
The updated version is available on the Pypi: https://pypi.org/project/fast-drf/2.2.10/
